In [2]:
import numpy as np

In [6]:
# Basic Numpy Functions

In [7]:
#.array will create an array of n-dimensions (initialized)
arr = np.array([7,8,9])

#.zeros will fill all index with zeroes, sames as .ones (need to specify array capacity)
np.zeros(2)


array([0., 0.])

In [8]:
#.empty creates an empty n-dimension array with random values dependent on tate of memory, etc (need to specify n-value)
np.empty(4)

array([1.57867127e-311, 1.57664287e-311, 7.80623720e-321, 3.79442416e-321])

In [10]:
#.arange lists a range of values from a to b, can also specify increment (last param)
np.arange(3,30, 3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [15]:
#functions such as .ndim, .size, .shape will return attributes about the given ndarray
test = np.array([[[2,45],
                [5,2],
                [6,19],
                [24,61]]])
#.ndim returns the #of axes or dimensions (num of square brackets)
test.ndim

3

In [17]:
#.size returns total number of elements
test.size

8

In [18]:
#.shape returns the dimesion and size/number of elements in a tuple
test.shape

(1, 4, 2)

In [20]:
#.reshape changes the shape of an array without changing the dimensions (specify rows and columns as a tuple)
a = np.arange(6)
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]
