In [1]:
import numpy as np

# Basic Numpy Functions

In [2]:
#.array will create an array of n-dimensions (initialized)
arr = np.array([7,8,9])

#.zeros will fill all index with zeroes, sames as .ones (need to specify array capacity)
np.zeros(2)


array([0., 0.])

In [3]:
#.empty creates an empty n-dimension array with random values dependent on tate of memory, etc (need to specify n-value)
np.empty(4)

array([2.12199579e-314, 0.00000000e+000, 4.88136858e-321, 1.19892762e-311])

In [4]:
#.arange lists a range of values from a to b, can also specify increment (last param)
np.arange(3,30, 3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [5]:
#functions such as .ndim, .size, .shape will return attributes about the given ndarray
test = np.array([[[2,45],
                [5,2],
                [6,19],
                [24,61]]])
#.ndim returns the #of axes or dimensions (num of square brackets)
test.ndim

3

In [6]:
#.size returns total number of elements
test.size

8

In [7]:
#.shape returns the dimesion and size/number of elements in a tuple
test.shape

(1, 4, 2)

In [8]:
#.reshape changes the shape of an array without changing the dimensions (specify rows and columns as a tuple)
a = np.arange(6)
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [9]:
#.sort will sort via row
np.sort(test)

array([[[ 2, 45],
        [ 2,  5],
        [ 6, 19],
        [24, 61]]])